version: '3.8'

services:
  teacher-workload-app:
    build: .
    container_name: teacher-workload-app
    ports:
      - "8888:3000"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
    volumes:
      - data_volume:/app/data

volumes:
  data_volume:
